[package]
name = "odra_amm"
version = "0.1.0"
edition = "2021"

[dependencies]
odra = { version = "0.5.0", features = [], default-features = false }

[features]
default = ["mock-vm"]
mock-vm = ["odra/mock-vm"]
casper = ["odra/casper"]
